#ifndef __PROTOCOLS__
#define __PROTOCOLS__

#define CODE_REGISTER_PUBLISHER 1

#define CODE_REGISTER_SUBSCRIBER 2

#define CODE_CREATE_BOX_REQUEST 3

#define CODE_CREATE_BOX_RESPONSE 4

#define CODE_REMOVE_BOX_REQUEST 5

#define CODE_REMOVE_BOX_RESPONSE 6

#define CODE_LIST_BOXES_REQUEST 7

#define CODE_LIST_BOXES_RESPONSE 8

#endif